### ISSUE TITLE
Watching videos does not accumulate points

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2864]
Branch: develop

Logged in as a student I apparently don't accumulate points as I watch videos. To reproduce, log in as student, watch a video, and observe your points remaining the same.

**Comment by aronasorman** [comment]
Pretty important. @rtibbles or @jamalex can you guide @MCGallaspy on how to fix this?

**Comment by rtibbles** [comment]
This may be related to #2865, but more likely I have simply ballsed up @jamalex's previously elegant code to regularly poll VideoJS to get points updates.

This is probably best fixed by attaching a callback to the timeupdate (https://github.com/videojs/video.js/blob/master/docs/api/vjs.Player.md#timeupdate-event) event on VideoJS. You can find the placeholder code for this in distributed/static/js/video/views.js on line 120 (currently commented out and with no callback function) - self.update_progress() should be moved in here from 'durationchange'.

**Comment by MCGallaspy** [comment]
Made the suggested change with the timeupdate callback, but in my limited testing this issue remains unresolved. Seems to be an issue with the ContentBaseView `update_progress` method in /distributed/static/js/distributed/content/views.js, namely execution is returned early because `!this.active` is always true.

I want to write a test for this, but I'm foiled for now because I'm unable to download any videos... will revisit this issue.
