### ISSUE TITLE
Multiple Students can't log in anymore with the following error message: AssertionError

### ISSUE THREAD

**Issue by ruancilliers** [learningequality/ka-lite#3421]
Branch: 0.12.0
Expected Behavior: I expect students to be able to log-in and carry on with their work. I now have to create a new log-in although their data is still in the database (See screen shot, as an example look at student iviwe dumayo.) 
Current Behavior: Whenever I try to log-in with this student, I get the following Assertion Error:
AssertionError: There should never be multiple summaries in the same time period/device/user/type combo

Please let me know how to fix this error: Ruan.Cilliers@gmail.com Thank you!

Steps to reproduce: Just try to log-in with student Iviwe Dumayo. (See Screen shots attached)
![assertion error](https://cloud.githubusercontent.com/assets/11680550/6869066/cb08fabe-d499-11e4-841a-5ddf56b64b07.JPG)
![dumayo iviwe](https://cloud.githubusercontent.com/assets/11680550/6869067/cb256852-d499-11e4-917e-00a993a1f294.JPG)

![image](https://cloud.githubusercontent.com/assets/11680550/6869092/018d2c0e-d49a-11e4-95bb-b154c1ad5ae7.png)
![image](https://cloud.githubusercontent.com/assets/11680550/6869106/17ce3e5e-d49a-11e4-9cc5-1ff4ccb04e73.png)

**Comment by rtibbles** [comment]
@jamie do we need to move the hotfix for this to 0.12? or is it already there?

**Comment by ruancilliers** [comment]
Dear Khan Lite Support Team,

Is there any progress on this issue? 

Let me know if I can assist in any other way for debugging purposes. You can also long into my server using TeamViewer if needed.

Let me know... Kind Regards,
Ruan

**Comment by jamalex** [comment]
@ruancilliers I believe this was fixed in a recent 0.12.x patch release (over a month ago now), and should be fixed in the latest master branch version (0.12.11). Can you clarify what exact version you're running on (you said "Branch: 0.12.0", but that's not the name of a branch, and version 0.12.0 would be very old). Try checking out master and pulling the latest version from there, and restarting.

**Comment by ruancilliers** [comment]
Dear Jamie,

I pulled the latest master from GIT and did an update on my Khan Lite
Server. This was done on 8 April, so I should be on the branch version
(0.12.11) - For interest sake, with which command can I check on which
version I'm on?

In any case as this is the latest version, I tried to access that user and
I still get the same error. Is there a log or something that I can send you
to verify the error or do you want to log into my server with Team Viewer
or a similar program?

Thank you for your support,
Ruan

**Comment by ruancilliers** [comment]
Hi Jamie,

Anything else that I can try as I still get the same error after updating
the server to the latest version?

Thank you for your help,
Ruan

**Comment by MCGallaspy** [comment]
> For interest sake, with which command can I check on which
version I'm on?

You should be able to see the version in the footer of the web app. I'm guessing your database is in an errored state somehow; sorry, I'm sure that's not very helpful, but it's difficult to say anything more substantial with the information you have provided. Can you provide more detailed steps on how to reproduce the error? I mean starting from creating the student account to reaching the given error.

**Comment by MCGallaspy** [comment]
Stale, but will reopen if we hear back from @ruancilliers.
