### ISSUE TITLE
0.14.0 Cookie is not expiring when the the browser is closed on remote clients.

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4399]
I have been experiencing this quite a bit while testing, it seems that from a remote machine after logging into a KA-Lite server instance as admin that if I then close the browser and reopen the browser to that same ip address, I am still logged in as before where the expected behavior is that the cookie would be deleted and I should have to select facility and provide username and password credentials to log back in.  This does not happen on the same machine that is hosting the KA-Lite server instance and seems to only happen on remote connections to that server. 

The use case I see this being an issue for is in a computer lab scenario with a dedicated server where the teachers and students are logging in using the same machines giving the students elevated privileges to the KA-Lite server instance.

**Comment by aronasorman** [comment]
What OS were you using?

**Comment by EdDixon** [comment]
In this case Windows 8.1 but I think I have sen this in prior tests using others as well I just need to go back and recheck for this.

**Comment by aronasorman** [comment]
My hunch here is that the browser isn't getting truly closed. Let me try instead setting the `SESSION_COOKIE_AGE` to 2 hours. Does that work @EdDixon?

**Comment by arceduardvincent** [comment]
I use the newly built installer in OS X using the `0.15.x` branch and use the `khan_assessment.zip` then I access the remote machine, after logging into a KA-Lite server instance as admin then close the browser and reopen the browser to that same ip address, I notice that the previous user is still logged in.

This issue is manifesting on `0.15.x` branch.

**Comment by djallado** [comment]
I tested the latest build by @arceduardvincent. I also perform the same process as what @arceduardvincent did, the issue still manifest in the latest build.

**Comment by rtibbles** [comment]
Fixed in #4411

**Comment by EdDixon** [comment]
Still exists in 0.15 on current development installer on Windows XP.. Please reopen!
