### ISSUE TITLE
Questions in learn exercise never end

### ISSUE THREAD

**Issue by manipalsingh013** [learningequality/ka-lite#4875]
When using exercise from learn, questions never end as they start repeating from the beginning and keep repeating.

Branch : **0.16.x**
OS: **Ubuntu 14.04**

Steps to reproduce:
1. Login as a Learner
2. Choose any exercise from learn
3. Keep answering question

Expected Behavior: Once all the question in exercise are answered by learner, he/she should get a notification regarding exercise completed.
Current Behavior: Question never end, they start to repeat from beginning and keep repeating.
![exercise](https://cloud.githubusercontent.com/assets/13970876/13178558/7ce9a770-d745-11e5-92e3-18d44f109665.png)

**Comment by manipalsingh013** [comment]
I noticed that Progress bar is full i.e Quiz is complete but all questions are not covered till then, repetition starts few questions later(in some exercises)

**Comment by manipalsingh013** [comment]
@rtibbles I would like to work on this, but what should be the fix?
Is it fine giving learner some alert?or it should be something else?

**Comment by j-schwartz** [comment]
Hi Guys - I'm getting the same behavior on 0.16.5 for all exercises... This would seem like a bigger deal, no?

**Comment by rtibbles** [comment]
I guess I am missing the point here - when the student has been judged as 'mastered' the exercise, they should get a notification.

If a student choose to continue practicing, then they will be able to continue to take the exercise for extra practice if they so wish.

I guess what I am saying is: this is intended behaviour, but perhaps the user experience is not as good as it could be if people don't realize they have achieved mastery?

**Comment by j-schwartz** [comment]
Ah, what would the notification look like?  Just the green bar filling up?  I guess in the past I felt like when a subject was mastered they were moved on (or at least presented an option to move on) to the next video.

It seems like a bigger issue because when a user finishes watching a video, there is an error that doesn't automatically move them on to the exercises, so this seemed to me at least, to be a similar error.

https://github.com/rachelproject/rachelplus/issues/56

**Comment by rtibbles** [comment]
There should be, and perhaps something is awry here, a notification bar (blue in colour) that appears above the exercise frame, saying "You have finished this exercise".

Note: none of these messages will appear if no user is logged in, or the user is either a coach or an admin - these messages will only appear for student accounts.

The error in the link above looks like the error that might occur if watching a video as an admin (when it tries to save the VideoLog as an admin, it has no student user field, so cannot save the file).

If this is happening with student accounts, could you please replicate the error, and copy/paste the traceback from the Javascript console here?

**Comment by j-schwartz** [comment]
OK, great.  I'm not sure what the desired behavior is, but here's what I've got.  As a learner, after watching a video, nothing happens.  To move on to exercises or the next video, a learner must go to the content tree.

As an administrator, the error message appears: 

![image](https://cloud.githubusercontent.com/assets/9270388/15523994/6c038a10-21d3-11e6-87d0-bf17f7088ba3.png)

For exercises, as a learner, no blue notification bar appears.  

I don't know how to find a traceback from the Javascript console.  I'm looking up online 'traceback on javascript' or if you have instructions for it, I'll gladly do it.

**Comment by rtibbles** [comment]
Video wise, this sounds like expected behaviour - as long as no error is appearing for learners after watching videos, so I wouldn't worry so much about the Javascript console.

The lack of mastery notification is more concerning, I'll take a look into it.

**Comment by j-schwartz** [comment]
many thanks @rtibbles

**Comment by j-schwartz** [comment]
Maybe in the error bar, that says "sorry, ..." we could throw in a "confirm you are logged in as a user" as I know lots of usage still occurs while kids don't log in and that message may be discouraging.  It's a sad reality it is very difficult to get users to create logins, but we don't want to discourage them from learning still!

**Comment by rtibbles** [comment]
Good idea!

Any feedback you have about ways to make the login experience better/lower friction would be interesting.

We currently have the optional 'SIMPLIFIED_LOGIN' setting, that allows users just to type in their username, and doesn't require the password, but have been wondering if we could make it simpler still.

**Comment by j-schwartz** [comment]
In my experience, it's rare that kids are using the system one-on-one with a device.  I know that defeats a number of the features you have, by not having logins, but it shouldn't be discouraging or undervaluing how impactful a tool this is without the student tracking info.

My vote, would be to keep logging in entirely optional, such that not logging in, does not have any adverse effects on folks.  

Said another way, if I were developing this for the users I know, I would develop it in a way that not logging in doesn't have a negative impact on the experience.

The kids who do create logins, do it after months of watching videos and doing exercises without first logging in.  We don't want to lose their interest in the first months while they aren't logged in yet, by throwing obstacles or discouraging notes their way.

**Comment by j-schwartz** [comment]
From the perspective of a first time computer user, or at least first time KA-lite user, you have 90% fear or breaking something and 10% excitement.

There are lots of kids I have seen, who if they saw that sorry, something has gone wrong message, after first watching a video, who will immediately close the browser and walk away for fear they have done something wrong.

The investment in computers / ka-lite / time on hardware is massive relative to school budgets, and the fear of breaking something is one of the primary obstacles I see us trying to overcome to increase adoption.

**Comment by benjaoming** [comment]
> There are lots of kids I have seen, who if they saw that sorry, something has gone wrong message, after first watching a video, will immediately close the browser and walk away for fear they have done something wrong.

Important observation. Adding a ticket for easy pickings about it: #5123

**Comment by jamalex** [comment]
I do remember an error message like that, but it would only happen for admin users, not for other user types and also *not for users who aren't logged in at all*. So hopefully that would address these (very valid) concerns.

I remember we cleaned some things up a while back so that error shouldn't show for admin users either, and I haven't been able to replicate it (either as a superuser or a not-logged-in user) on the demo server:
http://demo.learningequality.org/

Is it possible you logged out in one tab and left the other tab running (but it didn't know that it had been logged out)? I could imagine that might lead to something like this.

**Comment by jamalex** [comment]
Nevermind, I replicated it -- only happens when the video ends naturally; there's some old code in there that tries to force a log save when the video finishes, without doing the "check that the user is logged in and isn't an admin" check that typically happens. Fix is incoming.

**Comment by jamalex** [comment]
Fix for the error message issue is in https://github.com/learningequality/ka-lite/pull/5124 -- thanks for reporting!

> To move on to exercises or the next video, a learner must go to the content tree.

This is "expected" behavior (we've never recommended specific follow-on content in KA Lite on the content pages, though that would of course be helpful, and is part of the design of Kolibri).

Are there any other things we've missed in this issue that are still outstanding?

**Comment by j-schwartz** [comment]
Fantastic, I think we still want to make sure some blue notification bar at least appears to let students know they have mastered the topic.  That seems to be missing in Ubuntu installs.

**Comment by benjaoming** [comment]
> Are there any other things we've missed in this issue that are still outstanding?

@jamalex not by my reading: Being able to repeat the exercises is a desired feature, but not seeing when you've mastered the level is the one remaining issue.

**Comment by radinamatic** [comment]
The green bar with checkmarks is still there (0.16.5 on Ubuntu 16.04) once the exercise has been "mastered" (correct 8 of 10 answers), but it still might be insufficient as a notification by itself: 

![selection_448](https://cloud.githubusercontent.com/assets/1457929/15581898/a7f477ea-236e-11e6-8a24-fe7f70145cfa.png)

Learners can, of course, continue doing the exercise, but we should think of adding an alert message to that effect:

```
Congrats, you have completed the "8 out of 10" questions for this exercise! You can continue until you finish all the questions here, or you can choose another exercise.
```

**Comment by j-schwartz** [comment]
Yes, I agree it's insufficient for a learner to realize they are done,
especially because they keep earning points.  A lot of kids may try to just
rack up points on easy questions for no real benefit.

I think the other thing, at least for me, would be the last part of the
note:

"You can continue until you finish all the questions here, or you can
choose another exercise."

Is that true?  Does one ever finish the questions?  It seems like you can
go on and on and though the questions repeat themselves, it might take
quite some time before a learner realized that.  The quoted part above
seems to imply to me that at some point a learner will "finish," which I'm
not sure is accurate or identified by any behavior when that actually
occurs.

**Comment by benjaoming** [comment]
@radinamatic - could you verify with the latest prerelease of 0.16.6 that this has been fixed?

**Comment by djallado** [comment]
The checkmarks continues even if I got 104 points. I'm using KA Lite MacOS installer.  
Here's my screenshot:
![check](https://cloud.githubusercontent.com/assets/8664071/16130860/9c6d43ae-343d-11e6-8e8f-dea2217a0da2.png)

**Comment by amodia** [comment]
I also tested this on windows 7 32 bit KA Lite v0.16.6. The checkmarks still continues after 104 points.

![screen shot 2016-06-17 at 3 58 46 am](https://cloud.githubusercontent.com/assets/8663934/16131348/5d23c742-3440-11e6-9041-644c5138ba79.png)

**Comment by j-schwartz** [comment]
@amodia @djallado I think we agreed that was OK, but that we would add a notice that the topic has been mastered once exceeding 100 points.  Does that notice appear?

**Comment by amodia** [comment]
@j-schwartz There's no notification shown that I exceeding 100 points.

**Comment by rtibbles** [comment]
@benjaoming How would this have been fixed? I did not submit a fix for it yet.

**Comment by benjaoming** [comment]
@rtibbles I don't think it's fixed, it was a fly-by misread. Previous comment is still extant:

> Being able to repeat the exercises is a desired feature, but not seeing when you've mastered the level is the one remaining issue.

**Comment by needlestack** [comment]
I'm seeing this listed as being fixed in 0.16.6: 

https://groups.google.com/a/learningequality.org/forum/m/#!topic/dev/_xc6W0VUYIs

Is that info correct? It's confusing because in addition to being listed as a bug fix it is listed as a "known issue" (with the same issue ID, but a different description) under the content packs. Any insight is appreciated!

**Comment by spatiald** [comment]
Not fixed in 0.16.6post1 or 0.16.7b1 - no "Mastered" notification other than the green bar and the points don't continue past 104 points.  I believe this is being working for 0.16.7 milestone still, can the devs confirm?
![kalite-tracking-possible-issue](https://cloud.githubusercontent.com/assets/5751915/16739187/ea202fda-4766-11e6-94c5-fdec74eae9e2.png)

**Comment by benjaoming** [comment]
@spatiald - you're absolutely right :( Unfortunately, there have been many issues to fix, and this one has not received a patch yet. If you look at the release notes for 0.16.7, I hope it gives hope that we didn't take stuff lightly, we just have to ship at some point and accept the state of improvements we've managed.

If we can manage to get a fix out for a 0.16.8 patch release, that would be okay.. then we should release it while still on 0.16.

Just for this particular issue, I think we should aim for 0.16.8.. otherwise, other issues should be redirected for a 0.17, unless just as serious.

**Comment by benjaoming** [comment]
Fixed in #5261!

Doing a release right meow because of the severity of the issue.

**Comment by radinamatic** [comment]
Confirming the fix meow (:smiley_cat:) in **0.16.9~b1-0ubuntu1**!

![selection_056](https://cloud.githubusercontent.com/assets/1457929/18320345/b66e03ec-7529-11e6-9442-a7e73e6f059d.png)

@benjaoming Seeing some `ReactMount` errors in the console but nothing in UI.
