### ISSUE TITLE
Video download still throws "TypeError: e is null" in the console

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4961]
## Summary

Happens on some videos `/early-math/cc-early-math-counting-topic/cc-early-math-counting` but not others `/early-math/cc-early-math-add-sub-basics/cc-early-math-add-sub-intro/`. 

It also happens after cancelling the download and trying to download those same cancelled videos again. 

Happens on English and other locales (es, fr, pt)

## Branch or installer method

Build 74 on OSX.

## How to reproduce

1. Select videos to download.
1. Cancel the process.
1. Try to download again.

## Screenshots

![e-null2](https://cloud.githubusercontent.com/assets/1457929/13512309/1570c268-e19a-11e5-8078-995b72f4a243.png)

**Comment by rtibbles** [comment]
Quite possible that this build does not include the fix, as it was only merged this morning by @benjaoming.

**Comment by radinamatic** [comment]
On UI side, the only noticeable thing is that when this error happens, user does not get the message `x of x videos downloaded successfully`.

**Comment by radinamatic** [comment]
That's the latest installer for OSX, any others that include this merge that I can test? @rtibbles

**Comment by rtibbles** [comment]
The latest debian builds already had the fix merged in.

**Comment by radinamatic** [comment]
Hmm, I think 0.16b1 is anterior to this one by @cpauya... 
I'll restart the debian VM and recheck.

**Comment by radinamatic** [comment]
Ok, this does seem fixed on 0.16b1, but is still an issue on build 74 for OSX. 
@cpauya, please make sure to include it in the next build! :smiley_cat:

**Comment by cpauya** [comment]
Hi @radinamatic - build 75 at http://dungeon.learningequality.org/browse/KL-MT16-75/artifact now has the fix mentioned.  

Here's a screenshot of the cancelled video download page on a Yosemite VM using Safari:

![screenshot 2016-03-04 19 08 04](https://cloud.githubusercontent.com/assets/175580/13525534/7485e182-e23c-11e5-886f-604b6804985f.png)

As you can see, I attempted to download and cancelled twice without the error in the Console (except for the 404 error for the missing .gif).

So I think this issue is fixed. :smile_cat:

**Comment by radinamatic** [comment]
Looks good, @cpauya :+1: 
Downloading build 75!

**Comment by radinamatic** [comment]
Fix confirmed on Windows XP (build 167).

**Comment by radinamatic** [comment]
Fix now confirmed on OSX Yosemite also (build 76)! :+1:
