### ISSUE TITLE
Ka Lite 0.16.6 server won't run after fresh installation

### ISSUE THREAD

**Issue by AcevedoMichael** [learningequality/ka-lite#5179]
## Summary
Hello Everyone,

  I recently came across Ka Lite and really want to put it to use for my 3 children since we are on Sattelite internet and we pay for each Gig KA Lite is a true blessing. However once I've installed the fresh install and also installed Python without any issues I can't seem to get the server to start. 
I've made sure my firewall isn't blocking Ka Lite or Python but the server still wont start when directed via the icon options. Am I missing something here? I've even searched on Youtube to create private servers and found myself spending about 4 hours and finally installed Apache MadCat and getting it to work to 127.0.01:8080.

I've already spent nearly 20 hours online trying to figure this out looking through most of the issues posted here, searching the KA Lite online user manual, I even found myself taking a course on creating Git commands I don't even know if that's correct but my point is this.
How come it's so difficult to install and run Ka Lite?? I am not a software engineer but I like to think I know enough to get around on a PC what am I missing here people?

I am in real need here guys. Any advice will be greatly appreciated. Thanks in advance.

*Briefly describe what this is about*

## Branch or installer method
I downloaded the installed located on the http://ka-lite.readthedocs.io/en/0.16.x/installguide/install_main.html

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Windows 7 Ultimate 64 Bit

or:

 - Branch: develop (?)

## Traceback or relevant snippet from server.log----- Server log not found!!

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by djallado** [comment]
@AcevedoMichael. After an installation, I can start server successfully without any issues. I'm using IE11 windows 7 32-bit. I will check this in windows 7 64-bit. 

I'm using installer from https://learningequality.org/r/windows-installer-0-16. 

From the windows installation guide:
```When you start the KA Lite program, you will find a leaf icon in your task tray. Right click on this icon to start/stop the server, open the application in a browser, or set other options:```

**Comment by aronasorman** [comment]
Note that this was indeed a bug from last week, but we managed to fix this
bug and create a new installer last Tuesday. Please redownload again and
see if the new installer fixes this issue!

**Comment by djallado** [comment]
Done testing in Windows 7 64-bit the same installer I test in Windows 7 32-bit. In 64-bit static files are not loaded.
Here's the snapshot: 
![screen shot 64-bit](https://cloud.githubusercontent.com/assets/8664071/16312132/f2b8211c-39a5-11e6-97c3-a8d9cbe738c9.png)

**Comment by nalf3in** [comment]
I have the same issue on windows 10 64 bit : It try to start the server forever

**Comment by AcevedoMichael** [comment]
I'm sorry to see this isn't an isolated issue. @aronasorman I re-downloaded the installer again on this Tuesday the 21st and still have the same issue.

**Comment by radinamatic** [comment]
I cannot replicate this on Windows 7 Ultimate 64 Bit, with the installer `KALiteSetup-0.16.6.post1.exe`.

KA Lite manages to load correctly:

![workspace 1_504](https://cloud.githubusercontent.com/assets/1457929/16328889/bfd62936-39de-11e6-88d0-084509beaf88.png)

@aronasorman @djallado `KALiteSetup-0.16.6.post1.exe` that I tested on Tuesday (Win 7 32 Bit) and this morning (Win 7 64 Bit) , was downloaded from [Mr. Pau's Dungeon build 27](http://dungeon.learningequality.org/browse/KL-MP016WIN-27/artifact), but note the slight differences in size from the one I downloaded just now from Pantry:

![workspace 1_505](https://cloud.githubusercontent.com/assets/1457929/16329199/325748e4-39e1-11e6-87c5-50b687b7259c.png)

Could it be that with the latest changes on Dungeon another installer was uploaded to Pantry and that's why @AcevedoMichael @nalf3in are having problems?

**Comment by djallado** [comment]
This is a sample snapshot when I install `KALiteSetup-0.16.6.post1.exe` in Windows 7 64-bit: 
![screen shot x86](https://cloud.githubusercontent.com/assets/8664071/16338042/917b1330-3a4c-11e6-9956-04372fb04b1e.png)

May be this is the cause why static files are not loaded.  I tested this in Windows 7 Ultimate 64 Bit and Windows 7 Enterprise 64 Bit.

**Comment by arceduardvincent** [comment]
I replicate the same issue like @djallado had.
If I used `32bit` windows it doesn't have any issue, but in the `64bit` windows this issue exist which is the static files are not showing.

Tested this installers in 32bit and 64bit.
Dungeon Server: http://dungeon.learningequality.org:8085/browse/KL-KALITE016-265/artifact
Pantry Source: http://pantry.learningequality.org/downloads/ka-lite/0.16/installers/windows/

**Comment by benjaoming** [comment]
@arceduardvincent @djallado 

Are the static files installed at all?

**Comment by arceduardvincent** [comment]
@benjaoming I will try to run it manually in the `windows 64bit` OS and check if the static files are installed.

**Comment by arceduardvincent** [comment]
Aha! I found some hint here @benjaoming .
We have some browser support problem here. In the `Internet Explorer` the static files are not loaded but if we load the KA-Lite application the static files are loaded.

![screen shot 2016-06-25 at 12 02 54 am](https://cloud.githubusercontent.com/assets/4099119/16343272/b236f4e2-3a68-11e6-863c-2e2e94e356d3.png)

**Comment by rtibbles** [comment]
Note, this is due to the version of IE being too old, so the javascript cannot run.

**Comment by benjaoming** [comment]
Which version of IE is this?

**Comment by radinamatic** [comment]
Good news! :+1: 

 @AcevedoMichael @nalf3in 
Can you confirm that you can open and run KA Lite with non IE browsers?

**Comment by arceduardvincent** [comment]
@rtibbles thanks for the info.
@benjaoming I used IE 8 for this testing

**Comment by benjaoming** [comment]
@arceduardvincent okay that one is not supposed to work, that's about everything we currently have in our "System Requirements" :)

@AcevedoMichael You mentioned that "it doesn't start", so I wouldn't assume it's the issue you've identified... ?

**Comment by radinamatic** [comment]
Didn't we stopped supporting IE8 prior to KA LIte 0.15?

**Comment by AcevedoMichael** [comment]
@radinamatic I use Google Chrome Version 51.0.2704.103 m. But I also tried it on IE11 with no success.

I really appreciate the help from everyone, but I am still having the same issues where the server wont start. It appears that when I run KALite via the icon on the desktop or in the Start menu it loads up the program but when I right click the icon and select start server nothing ever happens. 

Yesterday I downloaded the installer from Dungeon Server: http://dungeon.learningequality.org:8085/browse/KL-KALITE016-265/artifact

and did a fresh install after removing the old installation but still no luck.

I am not familiar with Python commands but when I try to start it there I get this.
![kalite snapshot](https://cloud.githubusercontent.com/assets/20103299/16354657/2acbfc18-3a69-11e6-8af7-5a3e7a97ac25.png)

I am at a lost here but will love to get this working for my wife and I as we plan to home school our children this new year. I am grateful for this community and the support you all provide I am only hoping that we can figure out the issue without taking too much time off your hands.

**Comment by benjaoming** [comment]
@AcevedoMichael the `kalite start` command i supposed to be run directly from command line. If you don't have that command available, try locating the folder of `kalite.bat` (something like `C:\Python\Scripts\? )

Go to the folder with `cd c:\path` and then you can run `kalite start`

**Comment by benjaoming** [comment]
Closing due to lack of user response and because the latest user comment was about an invalid issue.
